development:
  adapter: postgresql
  host: localhost
  database: soundboardify_development
  min_messages: warning
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>

test:
  adapter: postgresql
  host: localhost
  database: soundboardify_test
  min_messages: warning
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>

production:
  adapter: postgresql
  host: localhost
  database: soundboardify